# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'company addresses',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name="Company's Name")),
                ('phone_no', models.CharField(help_text='if your company has more than one phone number, separate them with a comma', max_length=500, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, help_text='If your company has more than one email separate them by a comma', max_length=500, verbose_name='Email Addresses')),
            ],
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to='contacts.CompanyDetail'),
        ),
    ]
