# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_companyaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name_plural': 'company addresses'},
        ),
    ]
