# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181105_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
