# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 07:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
