# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'SocialMediaLinks',
            },
        ),
        migrations.AddField(
            model_name='newsocialmedialink',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsocialmedialink',
            name='url',
            field=models.URLField(default='', max_length=300, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsocialmedialink',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='snippets.SocialMediaLinks'),
            preserve_default=False,
        ),
    ]
