# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_supportemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'support emails',
            },
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AddField(
            model_name='supportemail',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='snippets.SupportEmails'),
            preserve_default=False,
        ),
    ]
