# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
