# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutcompany_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name_plural': 'about company'},
        ),
    ]
